#!/usr/local/bin/fish
export LSCOLORS="exfxcxdxbxegedabagacad"
export CHEAT_EDITOR="/usr/local/bin/mvim -v"
export PATH="$PATH:$HOME/.rvm/bin"

# 定义vim 到 mvim
alias vi='/usr/local/bin/mvim -v'
alias vim='/usr/local/bin/mvim -v'
alias ce='export VISUAL=vim; crontab -e'

# utilities
# -------------------------------------------------------------------------------------------------
function localip --description "show local IP of your maschine"
    netstat -rn | grep 'default' | awk '{print $2}'
end

function publicip --description "show public IP of your machine"
    curl -s checkip.dyndns.org | grep -Eo '[0-9\.]+'
end

function randpw --description "generate a random password"
  dd if=/dev/urandom bs=1 count=16 2>/dev/null | base64 | rev | cut -b 2- | rev
end

function pkill --description "pkill a process interactively"
  ps aux | peco | awk '{ print $2 }' | xargs kill
end

function port --description "show who is listening to the port $argv"
  lsof -n -i4TCP:$argv | grep LISTEN
end

# FINDER sidebar
# -------------------------------------------------------------------------------------------------
alias restore_finder="cd ~/Library/Preferences; and  sudo find com.apple.finder.plist* -exec rm {} \;; and  killall Finder"

# COFNIG
# -------------------------------------------------------------------------------------------------
alias ss='cat ~/.ssh/config'

# yarn
# -------------------------------------------------------------------------------------------------
alias yi='yarn install'
alias ya='yarn global add'

# brew
# -------------------------------------------------------------------------------------------------
alias bi='brew install'
alias bs='brew search'

# TOOLs Software
# -------------------------------------------------------------------------------------------------
alias mx='cmatrix'
alias d="axel -n 10 -a"
alias g='googler --colors bjcxxy -n 8'
alias pw="pwgen"

# mobile development
# -------------------------------------------------------------------------------------------------
alias we='weex'

# music video
# -------------------------------------------------------------------------------------------------
alias youtube="mpsyt"

# system wide
# -------------------------------------------------------------------------------------------------
alias ..="cd ..; and  ls"
alias ...="cd ../..; and  ls"
alias version='echo nodejs; and  node -v; and  echo npm; and  npm -v; and  php -v; and  docker -v; and  zsh --version'
alias dusort='du -sckx * | sort -nr'
alias bk='cd $OLDPWD'
alias ttop='top -ocpu -R -F -s 2 -n30'
alias lh='ls -a | egrep "^\."'
alias l='ls -alh'
alias h='cd ~'
alias c='clear'
alias x="exit"
alias ae='vi ~/sites/awesome-macbook-setup/aliases/fish_aliases'
alias au='source ~/sites/awesome-macbook-setup/aliases/fish_aliases'
alias as='alias | grep '

alias ds_clean="find . -name '*.DS_Store' -type f -ls -delete"
alias show="defaults write com.apple.Finder AppleShowAllFiles -bool true; and killall Finder"
alias hide="defaults write com.apple.Finder AppleShowAllFiles -bool false; and killall Finder"
alias et="rm -rfv ~/.Trash"
alias rr="rm -rf "

# tree
# -------------------------------------------------------------------------------------------------
alias t='tree .'
alias t2='tree -L 2 .'
alias t3='tree -L 3 .'

# Git
# -------------------------------------------------------------------------------------------------
alias gr='git remote -v'
alias grp='git remote prune origin; and  gb'
alias gbd='git branch --merged | egrep -v "(^\*|master|dev)" | xargs git branch -d'
alias ga='git add '
alias gp='git push'
alias gpa='git add -A; git commit -m "updates"; and git push -f'
alias gst='git status'
alias gm='git commit -m'
alias gam='git commit --amend --no-edit'
alias gba='git branch -v -a'
alias gb='git branch'
alias gc='git checkout'
alias gu='git pull'
alias gcl='git clone'
alias gf='git reflog'
alias gl="git log --graph --decorate"
alias gmnf="git merge --no-ff"
alias greset='git reset --hard HEAD'
alias gtags='git ls-remote --tags'
alias gfc='git log -1 --format="%an %ae%n%cn %ce" '


# flutter * dart
# -------------------------------------------------------------------------------------------------
alias ios="open -a Simulator"
alias f='cd /Users/xzhou/sites/flutterProjects; and ls -al'
function fcreate --description "create flutter project and enter there"
    flutter create $argv; and f; and cd $argv; and ls -al;
end
alias fdevices="flutter devices"
alias frun="flutter run"


# Editor
# -------------------------------------------------------------------------------------------------
alias a="/usr/local/bin/atom"

# vagrant
# -------------------------------------------------------------------------------------------------
alias vssh="vagrant ssh"
alias vup="vagrant up"

# composer
# -------------------------------------------------------------------------------------------------
alias cb='composer browse'
alias cu='composer update'
alias cr='composer req'

# Symfony
# -------------------------------------------------------------------------------------------------
alias cc='bin/console c:c'
alias ccc='bin/console c:c; and bin/console --env=prod c:c'
alias dev='bin/console --env=dev'
alias prod='bin/console --env=prod'

# docker-compose
# -------------------------------------------------------------------------------------------------
alias dstart='docker-compose start'
alias dup='docker-compose up -d'
alias dstop='docker-compose stop'
alias dlog='docker-compose logs'

# docker
# -------------------------------------------------------------------------------------------------
alias dps='docker ps -a'
alias dia="docker images -a"
alias drmi="docker rmi -f"
alias drm="docker rm -f"

# tig
# -------------------------------------------------------------------------------------------------
alias ts='tig status'

# stretchly: a tool for make a good break
# -------------------------------------------------------------------------------------------------
alias stretchly_edit='vi ~/sites/github/stretchly/app/utils/'
alias stretchly_build='cd ~/sites/github/stretchly; and npm run dist '

# github
# -------------------------------------------------------------------------------------------------
alias github='cd ~/sites/github; and ls -al'
alias github_config='git config user.name "Xun Zhou"; and git config user.email "segentor@gmail.com"'
alias bitbucket='cd ~/sites/bitbucket; and ls -al'

# curl cheat.sh
# -------------------------------------------------------------------------------------------------
function ch
  curl cheat.sh/$argv
end


# php
# -------------------------------------------------------------------------------------------------
alias php56="brew unlink php71; and brew link php56; and php -v"
alias php71="brew unlink php56; and brew link php71; and php -v"

# kochzauber
# -------------------------------------------------------------------------------------------------
alias hello="k; and vagrant up"
alias bye='k; and vagrant halt; x '
alias hs='history | grep '
alias job='env EDITOR=vim crontab -e'

alias k='cd /Users/xzhou/lidl/kochzauber'
alias r='cd ~/lidl/research-day'
alias kssh='k; and vssh'
alias wiki='cd ~/sites/bitbucket/vikbert.bitbucket.io; code .; and cd ..; and docute vikbert.bitbucket.io'
alias io='cd ~/sites/github/vikbert.github.io; code .; and cd ..; and docute vikbert.github.io'
alias dreminder='cd ~/sites/github/dreminder; code .'


# koza tests
# -------------------------------------------------------------------------------------------------
function kt
  k; and vagrant ssh -c "APP_PORTAL=koza SETUP_BROKER=1 php /var/www/virtual/platform/current/vendor/bin/phpunit --filter $argv"
end
function ktx
  k; and vagrant ssh -c "APP_PORTAL=koza SETUP_BROKER=1 php-xdebug /var/www/virtual/platform/current/vendor/bin/phpunit --filter $argv"
end


alias kt-unit='k; and vagrant ssh -c "php /var/www/virtual/platform/current/vendor/bin/phpunit tests/Unit" '
alias kt-functional='k; and vagrant ssh -c "php /var/www/virtual/platform/current/vendor/bin/phpunit tests/Functional" '
alias kt-integration='k; and vagrant ssh -c "APP_PORTAL=koza SETUP_BROKER=1 php /var/www/virtual/platform/current/vendor/bin/phpunit tests/Integration" '
alias kt-tests='kt-unit; and kt-functional; and kt-integration'
function kt-behat
  LMCH_CI="APP_PORTAL=lmch bash /var/www/virtual/platform/current/bin/behat -p lmch_ci --tags ~@postfinance"
  KOZA_CI="APP_PORTAL=koza bash /var/www/virtual/platform/current/bin/behat -p koza_ci --tags ~@postfinance"
  KOZA_API="APP_PORTAL=koza bash /var/www/virtual/platform/current/bin/behat -p api --tags ~@postfinance"
  k; and vagrant ssh -c "$LMCH_CI; $KOZA_CI; $KOZA_API"
end
#alias kt-behat='k; and vagrant ssh -c "php /var/www/virtual/platform/current/vendor/bin/behat -p ci --tags \'smoke\'   " '
alias kt-admin='k; and vagrant ssh -c "cd /var/www/virtual/platform/current/; APP_PORTAL=koza bin/console kochzauber:user:create admin admin@test.de; APP_PORTAL=lmch bin/console kochzauber:user:create admin admin@test.de;"'
alias kcs='k; and vagrant ssh -c "php /var/www/virtual/platform/current/vendor/bin/php-cs-fixer fix  -v 2> /dev/null; php vendor/bin/phpstan analyse -c phpstan.neon -l 1 src/"'
alias kinit='k; and vagrant ssh -c "echo \'cd /var/www/virtual/platform/current/\' >> .bashrc"'
alias ksetup='k; and vagrant ssh -c "bash /opt/lidl/ansible/kozang-setup-apps.sh"'
alias kcc='k; and vagrant ssh -c "cd /var/www/virtual/platform/current/; APP_PORTAL=koza bin/console cache:clear"'
alias kconfig='k; and vagrant ssh -c "cd /var/www/virtual/platform/current/; yes | cp -rf app/config/koza/parameters.yaml.dist app/config/koza/parameters.yaml; yes | cp -rf app/config/lmch/parameters.yaml.dist app/config/lmch/parameters.yaml"'

# indi
# -------------------------------------------------------------------------------------------------
alias icc='k; and vagrant ssh -c "cd /var/www/virtual/platform/current/; APP_PORTAL=indi bin/console cache:clear"'
alias igulp='k; rm -rf  core/assets/indi/fonts         core/assets/indi/images         core/assets/indi/tmp         core/assets/indi/css         core/assets/indi/js         core/assets/indi/sprites; and vagrant ssh -c "cd /var/www/virtual/platform/current/; APP_PORTAL=indi npm run gulp:dev;"'

# grafana research
# -------------------------------------------------------------------------------------------------
alias grafana='cd /Users/xzhou/lidl/research-day/grafana/vagrant-grafana-graphite'


# Monitoring
# -------------------------------------------------------------------------------------------------
alias shell='cd /Users/xzhou/sites/shell/monitoring; and atom .'
alias m-consumer='bash ~/sites/shell/monitoring/queue.sh'
alias log='bash ~/sites/shell/monitoring/logging.sh'

# github projects
alias sf4='cd /Users/xzhou/sites/github/sf4-starter'
