#!/usr/local/bin/fish
export LSCOLORS="exfxcxdxbxegedabagacad"
export CHEAT_EDITOR="/usr/local/bin/mvim -v"
export PATH="$PATH:$HOME/.rvm/bin"

# 定义vim 到 mvim
alias vi='/usr/local/bin/mvim -v'
alias vim='/usr/local/bin/mvim -v'
alias ce='export VISUAL=vim; crontab -e'

# utilities
# -------------------------------------------------------------------------------------------------
function localip --description "show local IP of your maschine"
    netstat -rn | grep 'default' | awk '{print $2}'
end

function publicip --description "show public IP of your machine"
    curl -s checkip.dyndns.org | grep -Eo '[0-9\.]+'
end

function randpw --description "generate a random password"
  dd if=/dev/urandom bs=1 count=16 2>/dev/null | base64 | rev | cut -b 2- | rev
end

function pkill --description "pkill a process interactively"
  ps aux | peco | awk '{ print $2 }' | xargs kill
end

function port --description "show who is listening to the port $argv"
  lsof -n -i4TCP:$argv | grep LISTEN
end

# FINDER sidebar
# -------------------------------------------------------------------------------------------------
alias restore_finder="cd ~/Library/Preferences; and  sudo find com.apple.finder.plist* -exec rm {} \;; and  killall Finder"

# COFNIG
# -------------------------------------------------------------------------------------------------
alias ss='cat ~/.ssh/config'

# yarn
# -------------------------------------------------------------------------------------------------
alias yi='yarn install'
alias ya='yarn global add'

# brew
# -------------------------------------------------------------------------------------------------
alias bi='brew install'
alias bs='brew search'

# TOOLs Software
# -------------------------------------------------------------------------------------------------
alias mx='cmatrix'
alias d="axel -n 10 -a"
alias g='googler --colors bjcxxy -n 8'
alias pw="pwgen"

# mobile development
# -------------------------------------------------------------------------------------------------
alias we='weex'

# music video
# -------------------------------------------------------------------------------------------------
alias youtube="mpsyt"

# system wide
# -------------------------------------------------------------------------------------------------
alias ..="cd ..; and  ls"
alias ...="cd ../..; and  ls"
alias version='echo nodejs; and  node -v; and  echo npm; and  npm -v; and  php -v; and  docker -v; and  zsh --version'
alias dusort='du -sckx * | sort -nr'
alias bk='cd $OLDPWD'
alias ttop='top -ocpu -R -F -s 2 -n30'
alias lh='ls -a | egrep "^\."'
alias l='ls -alh'
alias h='cd ~'
alias c='clear'
alias x="exit"
alias ae='vi ~/sites/awesome-macbook-setup/aliases/fish_aliases'
alias au='source ~/sites/awesome-macbook-setup/aliases/fish_aliases'
alias as='alias | grep '

alias ds_clean="find . -name '*.DS_Store' -type f -ls -delete"
alias show="defaults write com.apple.Finder AppleShowAllFiles -bool true; and killall Finder"
alias hide="defaults write com.apple.Finder AppleShowAllFiles -bool false; and killall Finder"
alias et="rm -rfv ~/.Trash"
alias rr="rm -rf "

# tree
# -------------------------------------------------------------------------------------------------
alias t='tree .'
alias t2='tree -L 2 .'
alias t3='tree -L 3 .'

# Git
# -------------------------------------------------------------------------------------------------
alias gbu='git remote prune origin; and  gb'
alias gbd='git branch --merged | egrep -v "(^\*|master|dev)" | xargs git branch -d'
alias ga='git add '
alias gp='git push'
alias gst='git status'
alias gm='git commit -m'
alias gam='git commit --amend --no-edit'
alias gba='git branch -v -a'
alias gb='git branch'
alias gc='git checkout'
alias gu='git pull'
alias gcl='git clone'
alias gf='git reflog'
alias gl="git log --graph --decorate"
alias gmnf="git merge --no-ff"
alias greset='git reset --hard HEAD'
alias gtags='git ls-remote --tags'
alias gfc='git log -1 --format="%an %ae%n%cn %ce" '

# Editor
# -------------------------------------------------------------------------------------------------
alias a="/usr/local/bin/atom"

# vagrant
# -------------------------------------------------------------------------------------------------
alias vssh="vagrant ssh"
alias vup="vagrant up"

# composer
# -------------------------------------------------------------------------------------------------
alias cb='composer browse'
alias cu='composer update'
alias cr='composer req'

# Symfony
# -------------------------------------------------------------------------------------------------
alias cc='bin/console c:c'
alias ccc='bin/console c:c; and bin/console --env=prod c:c'
alias dev='bin/console --env=dev'
alias prod='bin/console --env=prod'

# docker-compose
# -------------------------------------------------------------------------------------------------
alias dstart='docker-compose start'
alias dup='docker-compose up -d'
alias dstop='docker-compose stop'
alias dlog='docker-compose logs'

# docker
# -------------------------------------------------------------------------------------------------
alias dps='docker ps -a'
alias dia="docker images -a"
alias drmi="docker rmi -f"
alias drm="docker rm -f"

# tig
# -------------------------------------------------------------------------------------------------
alias ts='tig status'

# php
# -------------------------------------------------------------------------------------------------
alias php56="brew unlink php71; and brew link php56; and php -v"
alias php71="brew unlink php56; and brew link php71; and php -v"

# kochzauber
# -------------------------------------------------------------------------------------------------
alias hello="k; and vagrant up"
alias bye='k; and vagrant halt; x '

alias k='cd /Users/xzhou/lidl/kochzauber'
alias r='cd ~/lidl/research-day'
alias kssh='k; and vssh'

# koza tests
# -------------------------------------------------------------------------------------------------
function kt
  k; and vagrant ssh -c "php /var/www/virtual/platform/current/vendor/bin/phpunit --filter $argv"
end

alias kt-unit='k; and vagrant ssh -c "php /var/www/virtual/platform/current/vendor/bin/phpunit tests/Unit" '
alias kt-functional='k; and vagrant ssh -c "php /var/www/virtual/platform/current/vendor/bin/phpunit tests/Functional  " '
alias kt-test='kt-unit; and kt-functional'
alias kt-behat='k; and vagrant ssh -c "php /var/www/virtual/platform/current/vendor/bin/behat -p ci --tags \'smoke\'   " '
alias kcs='k; and vagrant ssh -c "php /var/www/virtual/platform/current/vendor/bin/php-cs-fixer fix  -v 2> /dev/null; "'

# grafana research
# -------------------------------------------------------------------------------------------------
alias grafana='cd /Users/xzhou/lidl/research-day/grafana/vagrant-grafana-graphite'


#  ansible
# -------------------------------------------------------------------------------------------------
